version: '3.7'

services:
  mvpmatch-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.docker
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./db-provision:/docker-entrypoint-initdb.d/
