import {
  UNKNOWN_ERROR,
  BAD_REQUEST,
  INCORRECT_PRICE,
  NOT_FOUND,
  UNAUTHORIZED,
  RESOURCE_NOT_FOUND,
  PRODUCT_ALREADY_EXISTS,
  USER_ALREADY_EXISTS,
  NOT_ENOUGH_DEPOSIT,
  NOT_ENOUGH_PRODUCT_AMOUNT,
  INTERNAL_SERVER_ERROR,
  AUTHENTICATION_FAILED,
} from './ErrorMessages';

export {
  UNKNOWN_ERROR,
  BAD_REQUEST,
  INCORRECT_PRICE,
  NOT_FOUND,
  UNAUTHORIZED,
  RESOURCE_NOT_FOUND,
  PRODUCT_ALREADY_EXISTS,
  USER_ALREADY_EXISTS,
  NOT_ENOUGH_DEPOSIT,
  NOT_ENOUGH_PRODUCT_AMOUNT,
  INTERNAL_SERVER_ERROR,
  AUTHENTICATION_FAILED,
};
